/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingdemo;

/**
 *
 * @author Raishin
 */
public class NewStudent extends javax.swing.JPanel {

    /**
     * Creates new form NewStudent
     */
    public NewStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        studentName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        studentGrade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        studentMarks = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        msgLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(640, 480));
        setLayout(null);

        jLabel1.setText("Name");
        add(jLabel1);
        jLabel1.setBounds(120, 53, 50, 28);

        studentName.setText("Enter name");
        studentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNameActionPerformed(evt);
            }
        });
        add(studentName);
        studentName.setBounds(168, 59, 145, 22);

        jLabel2.setText("Grade");
        add(jLabel2);
        jLabel2.setBounds(117, 94, 34, 28);

        studentGrade.setText("Enter grade");
        add(studentGrade);
        studentGrade.setBounds(169, 94, 144, 22);

        jLabel3.setText("Marks");
        add(jLabel3);
        jLabel3.setBounds(117, 129, 34, 28);

        studentMarks.setText("Enter marks");
        add(studentMarks);
        studentMarks.setBounds(169, 132, 144, 22);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(138, 193, 61, 25);

        msgLabel.setText("Studnet Info:");
        add(msgLabel);
        msgLabel.setBounds(117, 246, 240, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void studentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        // TODO add your handling code here:
        String name=studentName.getText();
        int grade=Integer.parseInt(studentGrade.getText());
        float marks= Float.parseFloat(studentMarks.getText());
        //display these data in a lable
        msgLabel.setText("Student Info :"+name+" "+grade+" "+marks);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JTextField studentGrade;
    private javax.swing.JTextField studentMarks;
    private javax.swing.JTextField studentName;
    // End of variables declaration//GEN-END:variables
}
